services:
  - type: web
    name: haibazo-round2-backend
    env: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: book_review_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: book_review_db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: book_review_db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: book_review_db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: book_review_db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
databases:
  - name: book_review_db
    databaseName: book_review
    user: book_admin
    plan: free
